m (a)
m (a) s((a),(b)) m (b)
m (a) s((a),(b)) m (b) s((b),(c)) m (c)
m (a,b)
m (a,b) s((a,b),(c,d)) m (c,d)
m (a,b) s((a,b),(c,d)) m (c,d) s((c,d),(e,f)) m (e,f)
m (a,b,c)
m (a,b,c) s((a,b,c),(d,e,f)) m (d,e,f)
m (a,b,c) s((a,b,c),(d,e,f)) m (d,e,f) s((d,e,f),(g,h,i)) m (g,h,i)
m (a,b) s((a,b),(c,d)) m (c,d) s((c,d),(e,f,g)) m (e,f,g)
m (a,b,c) s((a,b,c),(d)) m (d) s((d),(e,f)) m (e,f)
( blah a,b ) ( left: (a,b), right: (c,d) ) ( blah c,d ) ( left: (c,d), right: (e,f,g) ) ( blah e,f,g )
