( a , n )
( a , n )
( a , n ), ( b , o )
( a , n ), ( b , o )
( a , n ), ( b , o ), ( c , p )
( (a,b) , n ), ( (c,d) , (o,p) )
( a , j , r )
( a , j , r )
( a , j , r )
( a , j , r ), ( b , k , s )
( a , j , r ), ( b , k , s )
( a , j , r ), ( b , k , s )
( a , j , r ), ( b , k , s ), ( c , l , t )
( a , j , r ), ( b , k , s ), ( c , l , t )
( a , j , r ), ( b , k , s ), ( c , l , t )
( a , j , r ), ( b , k , s ), ( c , l , t )
( a , f , m , v )
( a , f , m , v )
( a , f , m , v ), ( b , g , n , w )
( a , f , m , v ), ( b , g , n , w )
( a , f , m , v ), ( b , g , n , w ), ( c , h , o , x )
( a , f , m , v ), ( b , g , n , w ), ( c , h , o , x )
( a , e , j , q , v )
( a , e , j , q , v )
( a , e , j , q , v ), ( b , f , k , r , w )
( a , e , j , q , v ), ( b , f , k , r , w )
( a , e , j , q , v ), ( b , f , k , r , w ), ( c , g , l , s , x )
( a , e , j , q , v ), ( b , f , k , r , w ), ( c , g , l , s , x )
( 10 , 20 , 30 , 40 , 50 , 60 ), ( 11 , 21 , 31 , 41 , 51 , 61 )
( 10 , 20 , 30 , 40 , 50 , 60 , 70 ), ( 11 , 21 , 31 , 41 , 51 , 61 , 71 )
( 10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ), ( 11 , 21 , 31 , 41 , 51 , 61 , 71 , 81 )
